### ISSUE TITLE
Explore how a chatbot can be integrate in the learning modules

### ISSUE THREAD

**Issue by musayann** [dacadeorg/dacade-frontend-app#1049]
Explore ways to integrate a chatbot similar to the one for ICP and look for ways to make it compatible in multiple communities and different learning contents in dacade

https://icp-ai-chat-frontend.vercel.app/tutorial/typescript-smart-contract-101/

First maybe the icp chat bot needs to be refactored and changed it into a chatbot.
Should be in multiple communities.

Talk to yannick, dario, Abraham.

**Comment by Jonath-z** [comment]
Hey @sezeranoJchrisostome, I just wanted to bring a clarification! When I mentioned a chrome extension, I actually meant a widget. I referred to the chrome extension we created because it didn't require us to build any backend for it. Hope that clears things up!

**Comment by moritzfelipe** [comment]
Lets talk with @moritzfelipe and @darioaschero too.

**Comment by sezeranoJchrisostome** [comment]
> Hey [@sezeranoJchrisostome](https://github.com/sezeranoJchrisostome), I just wanted to bring a clarification! When I mentioned a chrome extension, I actually meant a widget. I referred to the chrome extension we created because it didn't require us to build any backend for it. Hope that clears things up! I also replaced the _extension style_ by _widget_

That sounds great!

**Comment by moritzfelipe** [comment]
Quickly check in with dario and yannick and moritz in the dacade daily on wednesday

**Comment by moritzfelipe** [comment]
First version, we will not integrate it completely but create a chat view that can go on top of the current UI. Dario will talk to araya about design.
