### ISSUE TITLE
Reward for the first 25 who gets above 70% of the points

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-frontend-app#1075]
Additionally, we have the normal prize.

Users who exceed the threshold receive an additional reward, even if they are not in the top 3. The top 3 should receive their special reward, as well as anyone else who meets the threshold.

This reward can adopt the existing SUBMISSION type, and we could create a new type for the hackathon reward. In this case, we would automatically reward users with that submission reward, since everyone with points above the threshold automatically qualifies, and we wouldn't have to modify the codebase. Then, we would distinguish the new hackathon reward on the frontend, based on its type. Currently, hackathon rewards are not sent automatically so it shouldn't be an issue to alter them

**Comment by serapieTuyishime** [comment]
PR for this is: https://github.com/dacadeorg/dacade-cloud-functions/pull/84
