### ISSUE TITLE
Changes for icp hackathon HUB

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-frontend-app#1076]
Elad, [20. Feb 2024 at 16:40:48]:
General comments: 
1. Can we avoid using Discord and send people to find their teams in our telegram? We can have a channel there for it as well 
2. Spiced will collaborate with us and will offer their alumni to join the international teams as their local experts. They have 2500 alumni and they will share it with them on the 28th. I think more alumni will join if the name of the hackathon will include Spiced. Will that be ok? We should also add a sentence about Spiced in the hackathon description.4. Should we also include a cash prize for each submission that get more than 90 points?  
3. Rating rubric - perhaps we should also give points based on localization implementation. 
4. We need to confirm with ICP that we can call ourselves Central Europe hub before publishing this. 

Small stuff:
1. "Submit! Once you have completed the challenge, only person needs to submit it at the end of this page" - should be "only one person". 
2. "You need to get 90% to get into the prize pool and earn prizes worth of USD 7,000." - should be 90 points and 10k. 
3. "Confirm your team - Make sure your teammates accept notification to confirm your team" - should notifications. I'm not sure what it means though

Moritz Felipe, [20. Feb 2024 at 16:54:11]:
1. Yes i’m sure that is not a problem.
2. Also ok, can you suggest a name?
3. I think that could be a bit more difficult to implement but i will check.
4. Could you elaborate or give an example.
5. Sure its on staging, we can adopt the name quickly.

__
Small stuff:
1. Will change.
2. Already reported.
3. Means that you will get a notification on dacade will need to be confirmed in order to create the team, will check how to make this more clear.

__
* ICP Hackathon Challenge, Spiced for Europe 
* ICP European Spiced

__

https://github.com/dacadeorg/dacade-course-data/blob/main/challege-data/icp_hackathon_challenge_europe_2024_02.json

**Comment by gabrielaacha** [comment]
General comments: 

1. I updated with this: 

"Open Telegram channel https://t.me/+0oJye8IwAuxkMDY0 and find your teammates to complete the challenge with you"

2. I updated with this: 

"Evolve your ICP smart contract into a fully functional dApp tailored for the Central European market. This challenge is for developers who previously participated in an ICP challenge, offering the opportunity to take your smart contract to the next level by creating an application and localizing it for Central Europe. This Hackathon is possible thanks to our collaboration with Spiced Academy. Learn more about the requirements here: (LINK)"

3. I updated with: 

"You need to get <strong>90 points</strong> to get into the prize pool and earn prizes worth of <strong>USD 10,000.</strong>. Earn some extra points through your localization's implementations."

4. Is that confirmed?

Small stuff:

1. changed
2. changed
3. not sure what I have to do

Title changed with: "ICP Hackathon Challenge, Spiced for Europe"

**Comment by gabrielaacha** [comment]
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/57134592/b727acc4-3136-445a-8966-96e4b8804b19)



![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/57134592/ac44c8a4-04c5-4f80-bb7e-3e45c7f27c1c)
