### ISSUE TITLE
UI fix: Mobile version for landing page

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1193]
Align the mobile design with the desktop design by changing the heading layout and also the numbered list. 
Design: https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1062%3A9060&mode=design&t=NKHyKvjxXmP7RY5d-1

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/7007b1f6-7c0e-4864-95c1-78380231ec85)

**Comment by moritzfelipe** [comment]
@techgirlonlinee give feedback

**Comment by techgirlonlinee** [comment]
<img width="342" alt="Screenshot 2024-05-07 at 14 05 02" src="https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/cca88f27-ac2b-4803-b71c-af38eb3c36f2">
<img width="368" alt="Screenshot 2024-05-07 at 14 04 59" src="https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/3a9d3b29-07ac-463d-9ae0-25170c06ede3">


lines need to look the same. they need to be consistent because they are the same component
