### ISSUE TITLE
UI fix: mobile community card on landing page

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1195]
Fix the padding to be 24px on all sides. Currently the bottom is 12px and the others are 24px. Also the spacings between the cards should be 8px. See design: https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1062%3A9060&mode=design&t=NKHyKvjxXmP7RY5d-1 

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/af1f509d-c6e3-4669-b169-f2f655d7d178)

**Comment by moritzfelipe** [comment]
@techgirlonlinee give feedback

**Comment by techgirlonlinee** [comment]
<img width="376" alt="Screenshot 2024-05-07 at 13 58 37" src="https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/2c9acb2d-cd5b-4f9b-b177-d3503338de34">
Center align the button

<img width="293" alt="Screenshot 2024-05-07 at 14 00 31" src="https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/4d44e299-8333-4e92-b87a-bc9f3dce30af">
the pill needs to align with the bottom of the huge icon
