### ISSUE TITLE
Open-sourced section on landing page

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1198]
Insert this section on all screen sizes on the landing page

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/7ad8a7e2-d7e9-4fa8-87ca-49934b7a7ecf)

 see design 
https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=242%3A10035&mode=design&t=d69nNRAmMNqURNhU-1

**Comment by serapieTuyishime** [comment]
The issue is arleady resolved
