### ISSUE TITLE
UI fix: title color on the challenge page

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1199]
Change the title colors according to this design

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/caf567bf-2d3f-4878-b499-d0fd09c5037e)

https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1072%3A9694&mode=design&t=d69nNRAmMNqURNhU-1

**Comment by moritzfelipe** [comment]
@techgirlonlinee give feedback
