### ISSUE TITLE
UI fix: scoreboard filter

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1200]
Change the padding between the title and list and also between the items in the list
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/4dc04826-d76d-4354-b7d2-7994e23e816e)

according to this design: https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=135%3A2902&mode=design&t=d69nNRAmMNqURNhU-1

**Comment by moritzfelipe** [comment]
Will be part of next release.
