### ISSUE TITLE
UI fix: hint message box

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1204]
Hint message box needs to be in blue, also with 12px padding

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/14063d8d-4d1e-45a2-bd56-ae72828d4601)

see design https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1072-9694&mode=design&t=uQgtXooV51ruTxpG-0

**Comment by serapieTuyishime** [comment]
Closely related to #1202
