### ISSUE TITLE
UI fix: challenge card in community page

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1208]
Current version of the wrong border, shading, font sizes

1) spacing between each text line in the text on the left side (from the title to the pill, pill to included learning modules) should be 16px (1rem) but is currently 1.5rem 
2) learning module text should be font small (14px) medium weight. it's currently 16px normal weight. also the color should be grey
3) double line on the bottom of the whole box when it should be a single line 
4) border on the right side of the left text box is missing

Current version:
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/09dfa4b1-ede2-4d3a-a393-e755695aa4d2)

Design:
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/6ddba79b-fc00-4db4-a394-1314ef15f35d)

**Mobile version** 
1) duplicated line on the top should be removed
2) remove margin top on top of the title

Current version: 
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/49897854/fa540770-3911-4294-9ee1-30dfabc548b6)

Fix: Counting of learning materials
- Call it: "x Learning materials included"
- Count the amount by adding courses and single learning modules together"

**Comment by moritzfelipe** [comment]
@techgirlonlinee give feedback
