### ISSUE TITLE
Implement job search feature

### ISSUE THREAD

**Issue by techgirlonlinee** [dacadeorg/dacade-frontend-app#1214]
**Overview:**
We need to provide a way where the user could link their learnings to real life applications, like applying for a job. This could benefit the students by reducing the entry point to job search and apply within our platform. Could potentially help the partners that are looking for talents to see that these students are already certified. 

**User journey**
The user who completed at least a challenge or a course sees an additional link on the nav that allows them to be able to click. When the user clicks the link, a modal pops up to explain more about how the user needs to fill out a form in the next page to be contacted on relevant job roles. The user are able to click on the button in the modal which opens a new tab of the google form. If the user closes the modal, they are taken back to the page that they're on and the overlay dissapears. 

**Goals:** 
- user to have an easy and seamless, yet guided experience of leaving the platform to fill out a google form

**Requirements:**
1) add an additional link to the nav (underlined in blue). See design here -> 
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/1242997/cdfc596e-fc20-435c-9432-d0c7da07bd60)
https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1587%3A8434&mode=design&t=y3czoV69n2LjTmmY-1
2) add a white background overlay when the link is clicked and slowly transition the modal to appear in the middle of the screen. see design here -> 
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/1242997/b7b0702d-2b6f-49d8-a229-0020276c061c)
when implementing the design, look out for:
-font size
-font weight
-details of the shadow of the modal
https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1587%3A8072&mode=design&t=y3czoV69n2LjTmmY-1

Link should lead to this form:
https://forms.gle/czmMN9L5Hh88aUQu6

**Comment by Odile078** [comment]
This feature needs a task on the backend to include the challenges completed in the user object response.
