### ISSUE TITLE
Style: Change the course card

### ISSUE THREAD

**Issue by serapieTuyishime** [dacadeorg/dacade-frontend-app#1230]
- [ ] The hexagon should have the primary color of the community.
- [ ] This is the location of the component: `src/components/cards/challenge/_partials/Learning.tsx`.
- [ ] think about moving the card to a different location since its now used globally.

This is the card: 

![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/70019756/04112f0c-9f21-4f33-bd10-2d205e678736)

Design: https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=2060-21030&mode=design&t=rmnZXEgDbWUo7Juu-4

**Comment by coolestnick** [comment]
Can I work on this?

**Comment by serapieTuyishime** [comment]
Hello @coolestnick !
Thank you for your interest! However, the backend feature of the issue is not yet available.
